name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-mcpb:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{ !github.event.pull_request.head.repo.fork && secrets.TAKUMI_GUARD_BOT_ID || '' }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:mcpb
      - uses: actions/upload-artifact@v6.0.0
        with:
          path: build/kintone-mcp-server.mcpb
          name: kintone-mcp-server.mcpb
          retention-days: 3

  build-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{ !github.event.pull_request.head.repo.fork && secrets.TAKUMI_GUARD_BOT_ID || '' }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm pack
      - uses: actions/upload-artifact@v6.0.0
        with:
          path: "kintone-mcp-server-*.tgz"
          name: kintone-mcp-server.tgz
          retention-days: 3
