name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-mcpb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:mcpb
      - uses: actions/upload-artifact@v6
        with:
          path: build/kintone-mcp-server.mcpb
          name: kintone-mcp-server.mcpb
          retention-days: 3

  build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm pack
      - uses: actions/upload-artifact@v6
        with:
          path: "kintone-mcp-server-*.tgz"
          name: kintone-mcp-server.tgz
          retention-days: 3
