name: build-dxt

on:
  pull_request:
  workflow_call:

jobs:
  build-dxt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: build dxt archive
        run: pnpm dxt:pack
      - name: upload build result
        uses: actions/upload-artifact@v4
        with:
          name: kintone-mcp-server
          path: build/kintone-mcp-server.dxt
