name: publish-branch-image
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma-separated list of tags for the Docker image (e.g., "1.0.0,latest"). If empty, branch name will be used.'
        required: false
        type: string
      push:
        description: "Whether to push the Docker image to registry"
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash -eo pipefail {0}

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.generate-tags.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tags
        id: generate-tags
        env:
          BRANCH_NAME: "${{ github.ref_name }}"
          INPUT_TAGS: "${{ inputs.tags }}"
        run: |
          # tagsが空の場合はブランチ名を使用
          if [ -z "$INPUT_TAGS" ]; then
            # ブランチ名をDocker tagに適した形式に変換（/を-に置換）
            FINAL_TAGS=$(echo "$BRANCH_NAME" | sed 's/\//-/g')
          else
            FINAL_TAGS="$INPUT_TAGS"
          fi
          echo "result=$FINAL_TAGS" >> "$GITHUB_OUTPUT"

  build-and-publish-container:
    needs: generate-tags
    permissions:
      contents: read # To checkout in the reusable workflow
      packages: write # To push Docker image to ghcr.io
    uses: ./.github/workflows/publish-image.yaml
    with:
      tags: ${{ needs.generate-tags.outputs.tags }}
      push: ${{ inputs.push }}
